# Generated by Django 3.1.1 on 2020-10-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20201008_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='direction',
        ),
    ]
