# Generated by Django 3.1.1 on 2020-10-08 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_remove_employee_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='direction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='activities.direction'),
            preserve_default=False,
        ),
    ]
