# Generated by Django 3.1.1 on 2020-10-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20201008_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='direction',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
