# Generated by Django 3.1.1 on 2020-10-08 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_auto_20201008_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.direction'),
        ),
        migrations.AlterField(
            model_name='departmentdirector',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.direction'),
        ),
        migrations.AlterField(
            model_name='officeclerk',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.department'),
        ),
        migrations.AlterField(
            model_name='officeclerk',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.office'),
        ),
    ]
