# Generated by Django 3.1.1 on 2020-10-08 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_auto_20201008_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.direction'),
        ),
    ]
