# Generated by Django 3.1.1 on 2020-10-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_auto_20201008_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentdirector',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.department'),
        ),
        migrations.AlterField(
            model_name='officeclerk',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.department'),
        ),
        migrations.AlterField(
            model_name='officeclerk',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.office'),
        ),
    ]
