# Generated by Django 3.1.1 on 2020-10-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_auto_20201008_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='office',
            new_name='department',
        ),
    ]
