# Generated by Django 3.1.1 on 2020-10-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_auto_20201009_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
