# Generated by Django 3.1.1 on 2020-10-10 16:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_auto_20201010_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 19, 34, 51, 873579), verbose_name='release_date'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_set', to='activities.activity'),
        ),
    ]
