# Generated by Django 3.1.1 on 2020-10-10 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_auto_20201010_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='isShown',
            new_name='is_shown',
        ),
        migrations.AlterField(
            model_name='notification',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 20, 0, 38, 906801), verbose_name='release_date'),
        ),
    ]
