# Generated by Django 3.1.1 on 2020-10-12 12:38

import activities.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_auto_20201011_1351'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='departmentdirector',
            managers=[
                ('objects', activities.models.DepartmentDirectorManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='officeclerk',
            managers=[
                ('objects', activities.models.OfficeClerkManager()),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 15, 38, 32, 483357), verbose_name='release_date'),
        ),
    ]
