# Generated by Django 3.1.1 on 2020-10-12 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0020_auto_20201012_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='numberOfTasks',
            new_name='number_of_tasks',
        ),
        migrations.AlterField(
            model_name='notification',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 16, 48, 39, 574321), verbose_name='release_date'),
        ),
    ]
